name: Python test typeguard
on: [push, pull_request]

jobs:
  test-typeguard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python '3.11'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # install the current zigzag-dse
          pip install .[dev]
      - name: Test with pytest and typeguard
        run: |
          pip install pytest
          python -m pytest --typeguard-packages=zigzag tests/main/test_imc/test_dimc.py
          python -m pytest --typeguard-packages=zigzag tests/main/test_origin/test_meta_prototype_like.py
          python -m pytest --typeguard-packages=zigzag tests/main/test_with_mix_spatial_mapping/test_edge_tpu_like.py
          python -m pytest --typeguard-packages=zigzag tests/main/test_with_exploit_data_locality/test_ascend_like.py

